kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "ibm-connectivity-pack.role" .}}
  namespace: {{ include "ibm-connectivity-pack.namespace" . }}
  labels:
    {{- include "ibm-connectivity-pack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - create
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - get
      - list
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - get
      - list
      - create
      - patch
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - update
      - delete
      - create
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - update
      - delete
      - create
      - list
    apiGroups:
      - appconnect.ibm.com
    resources:
      - configurations

---
{{- if eq .Values.skipHooks false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "ibm-connectivity-pack.namespace" . }}
  labels:
    {{- include "ibm-connectivity-pack.labels" . | nindent 4 }}
  name: {{ include "ibm-connectivity-pack.preHookJobRole" . }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, post-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "update", "patch", "delete"]
{{ end }}