{{- if .Values.route.enable -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ibm-connectivity-pack.service" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-connectivity-pack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "ibm-connectivity-pack.service" . }}
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{ end }}