###############################################################################
#
# © Copyright IBM Corp. 2025
#
###############################################################################
# Default values for IBM Connectivity pack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skipHooks: false
namespace: ''
license:
  accept: false
replicaCount: 1 # Replica of the POD
bunyan: "'{\"loglevel\" : \"info\", \"logsrc\" : true, \"logstdouttext\" : {}}'" # Override Log configuration
environmentVariables: {} # Yaml object ENV to be added on action and event pods
enableRefreshTokenMode: false
annotations:
  productName: IBM Connectivity pack
image:
  registry: cp.icr.io # Image registry base URL
  path: cp/ibm-eventstreams
  imagePullSecretName: '' # Image pull secret name if already  exist please specify here else give below values for creating new Image pull secret
  imagePullEmail: dummyEmail # Image pull secret email ID
  imagePullUsername: iamapikey # Image pull username 
  imagePullPassword: ibm-entitlement-key # Image pull password 
certificate:
  enable: true # Enable MTLS or TLS
  MTLSenable: true # Enable MTLS if true else fallback to TLS
  generate: true # generate new certificates use this for certificate rotation
  clientSecretName: '' # If MTLS/TLS secret for client already exist please specify here
  clientCertPropertyName: 'tls.crt'
  clientCertKeyPropertyName: 'tls.key'
  clientCertPKCSPropertyName: 'pkcs.p12'
  serverSecretName: '' # If MTLS/TLS secret for server already exist please specify here
  serverCertPropertyName: 'tls.crt'
  serverCertKeyPropertyName: 'tls.key'
  caCertPropertyName: 'ca.crt'
  pkcsPassword: '' # pkcs.p12 password
route:
  enable: false # generate OpenShift route for external access
  domain: 'example.com' # subdomain of OpenShift cluster where connector service is being deployed
basicAuth:
  enable: false # Enable basic auth for service 
  username: 'csuser'
preHook:
  image: connectivity-pack-prehook
  digest: sha256:c544bc6336c92e6002042fc8fdd84d2b5e2d09ca6e8cd53d9a4575ea3c2bf14f
  tag: 2.0.0
proxy:
  name: connectivity-pack-proxy
  image: connectivity-pack-proxy
  digest: sha256:887bb7629a16f5246e8777bc4cf2707347d4c537461f0bd4aa523cb84145df6d
  tag: 2.0.0
action:
  name: action-connectors
  fileStreamingTimeout: '120000'
  maxFileSize: '262144000'
  image: action-connectors
  digest: sha256:800b56a821200174ac82e12d5b2649434c1fdadfc1d2061d02be99fe3b4cedd7
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 256Mi
  tag: 2.0.0
event:
  enable: true # Set to true if Event container is needed
  name: event-connectors
  image: event-connectors # Update image
  digest: sha256:2368806303cbc30420bd0ba63274219a7d8f4c359dfe378f38624c6d15db26bc
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 2.0.0
javaservice:
  enable: false
autoScaling:
  enable: false # Update this to true to enable autoScaling
  minReplicas: 1 # What is the minimum replica needed
  maxReplicas: 5 # What is the maximum replica needed
  cpuUtilization: 70 # % of CPU utilization after which POD to be replicated 
  memoryUtilization: 70 # % of Memory utilization after which POD to be replicated 
securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
csCommon:
  eventList: "['salesforceevent','jira','github','googlecalendar','googlebigquery']"
