###############################################################################
#
# © Copyright IBM Corp. 2024
#
###############################################################################
# Default values for IBM Connectivity pack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

license:
  accept: false
replicaCount: 1 # Replica of the POD
bunyan: "'{\"loglevel\" : \"info\", \"logsrc\" : true, \"logstdouttext\" : {}}'" # Override Log configuration
environmentVariables: {} # Yaml object ENV to be added on action and event pods
annotations:
  productName: IBM Connectivity pack
image:
  registry: cp.icr.io # Image registry base URL
  path: cp/ibm-eventstreams
  imagePullSecretName: '' # Image pull secret name if already  exist please specify here else give below values for creating new Image pull secret
  imagePullEmail: dummyEmail # Image pull secret email ID
  imagePullUsername: iamapikey # Image pull username 
  imagePullPassword: ibm-entitlement-key # Image pull password
certificate:
  MTLSenable: true # Enable MTLS if true else fallback to TLS
  generate: true # generate new certificates use this for certificate rotation
  clientSecretName: '' # If MTLS/TLS secret for client already exist please specify here
  clientCertPropertyName: 'tls.crt'
  clientCertKeyPropertyName: 'tls.key'
  clientCertPKCSPropertyName: 'pkcs.p12'
  serverSecretName: '' # If MTLS/TLS secret for server already exist please specify here
  serverCertPropertyName: 'tls.crt'
  serverCertKeyPropertyName: 'tls.key'
  caCertPropertyName: 'ca.crt'
  pkcsPassword: "" # pkcs.p12 password
route:
  enable: false # generate OpenShift route for external access
  domain: 'example.com' # subdomain of OpenShift cluster where connector service is being deployed
basicAuth:
  enable: false # Enable basic auth for service 
  username: 'csuser'
preHook:
  image: connectivity-pack-prehook
  digest: sha256:8afeb815d0f561e301202e3e172cbca6203b7ac07e51cbd530bdabd2d627bfd1
  tag: 1.0.1
proxy:
  name: connectivity-pack-proxy
  image: connectivity-pack-proxy
  digest: sha256:52742e0590c341dc133aa83c07afddcdb8723b5368028e6f1122ffd5e8882300
  tag: 1.0.1
action:
  name: action-connectors
  image: action-connectors
  digest: sha256:e83c2136687205e86d0535d76b73ce258ef8cf115e6143f8281b89e188c2975f
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 256Mi
  tag: 1.0.1
event:
  enable: true # Set to true if Event container is needed
  name: event-connectors
  image: event-connectors # Update image
  digest: sha256:05d28ddbd76ac49ca55b1672be084f3a4d50eb8f6f4aec020ce83fb6a8c153ca
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 1.0.1
javaservice:
  enable: false
autoScaling:
  enable: false # Update this to true to enable autoScaling
  minReplicas: 1 # What is the minimum replica needed
  maxReplicas: 5 # What is the maximum replica needed
  cpuUtilization: 70 # % of CPU utilization after which POD to be replicated 
  memoryUtilization: 70 # % of Memory utilization after which POD to be replicated 
securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
csCommon:
  eventList: "['salesforceevent']"
