###############################################################################
#
# © Copyright IBM Corp. 2024
#
###############################################################################
# Default values for IBM Connectivity pack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skipHooks: false
namespace: ''
license:
  accept: false
replicaCount: 1 # Replica of the POD
bunyan: "'{\"loglevel\" : \"info\", \"logsrc\" : true, \"logstdouttext\" : {}}'" # Override Log configuration
environmentVariables: {} # Yaml object ENV to be added on action and event pods
enableRefreshTokenMode: false
annotations:
  productID: "0c44732a8b794b2d9e9b842b2dfc8361"
  productName: "IBM Connectivity Pack - Free"
  productMetric: "FREE"
  productChargedContainers: "All"
image:
  registry: cp.icr.io # Image registry base URL
  path: cp/ibm-eventstreams
  imagePullSecretName: '' # Image pull secret name if already  exist please specify here else give below values for creating new Image pull secret
  imagePullEmail: dummyEmail # Image pull secret email ID
  imagePullUsername: iamapikey # Image pull username 
  imagePullPassword: ibm-entitlement-key # Image pull password 
certificate:
  enable: true # Enable MTLS or TLS
  MTLSenable: true # Enable MTLS if true else fallback to TLS
  generate: true # generate new certificates use this for certificate rotation
  clientSecretName: '' # If MTLS/TLS secret for client already exist please specify here
  clientCertPropertyName: 'tls.crt'
  clientCertKeyPropertyName: 'tls.key'
  clientCertPKCSPropertyName: 'pkcs.p12'
  serverSecretName: '' # If MTLS/TLS secret for server already exist please specify here
  serverCertPropertyName: 'tls.crt'
  serverCertKeyPropertyName: 'tls.key'
  caCertPropertyName: 'ca.crt'
  serverKeyStrorePKCSPropertyName: 'server.p12'
  serverTrustStorePKCSPropertyName: 'truststore.p12'
  pkcsPassword: '' # pkcs.p12 password
route:
  enable: false # generate OpenShift route for external access
  domain: 'example.com' # subdomain of OpenShift cluster where connector service is being deployed
basicAuth:
  enable: false # Enable basic auth for service 
  username: 'csuser'
preHook:
  image: connectivity-pack-prehook
  digest: sha256:6d38a8f6d32750dd832e61dcb484d555fe8d5f66d212d2505200d1c3342103e9
  tag: 3.1.0
action:
  name: action-connectors
  fileStreamingTimeout: '120000'
  udaPersistentVolumeClaimName: ''
  maxFileSize: '262144000'
  image: action-connectors
  digest: sha256:74c16dcb6fc04f09f924584979600de15d6ec47dd9206509a0de72375bd19120
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 3.1.0
event:
  enable: true # Set to true if Event container is needed
  name: event-connectors
  image: event-connectors # Update image
  digest: sha256:71139de912870c6d072dc42ce6690ce47b6dc809f62275a467c317ae53c4fab7
  resources: # Update below value for vertical scaling of container
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 750Mi
    requests:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 400Mi
  tag: 3.1.0
javaservice:
  enable: false
autoScaling:
  enable: false # Update this to true to enable autoScaling
  minReplicas: 1 # What is the minimum replica needed
  maxReplicas: 5 # What is the maximum replica needed
  cpuUtilization: 70 # % of CPU utilization after which POD to be replicated 
  memoryUtilization: 70 # % of Memory utilization after which POD to be replicated 
securityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
csCommon:
  eventList: "['salesforceevent','jira','github','googlecalendar','googlebigquery','servicenow','hdfsevent']"
mcp:
  enable: false # Update this to true to enable mcp server running as HTTP Streamaable  require tools and account config to give 
  accountsSecretName: '<name>' # Give the name of the secret which contains configuration key with accounts.yaml structure.
  toolsSecretName: '<name>' # Give the name of the secret which contains configuration key with tools.json structure.
  oauth:
    enable: false # enables aouth details
    settings: '{ "baseIdpUrl": "<idpUrl>", "wellKnownOAuthMetdataUrl": "<idpUrlwithMetaUri>", "scopesSupported": ["mcp:read", "mcp:tools", "mcp-server-audience"], "oauthAudience": "mcp-server", "clientRegistrationEndpoint": "<>", "mcpMethodRoleMapping": {    "tools/list": ["mcp:read"] ,   "tools/call": ["mcp:tools"]}, "clientDetails": {    "clientId": <>,    "clientSecret": <> } }'
